mozilla/chronicle

README.md
grunttasks/build.js
grunttasks/requirejs.js
grunttasks/serve.js
grunttasks/watch.js
npm-shrinkwrap.json
package.json

Watch is now configured to call specific tasks when certain files change. This will be more work to maintain but the performance should be much better as the project grows. The `requirejs` task now has `development` and `production` targets to improve performance when using `grunt serve`.

chore(build): Improved performance of watch and build tasks

---

npm-shrinkwrap.json
package.json

Fixed a couple outdated dependencies and removed an odd "jshint" dependency (odd because that should be included via grunt-contrib-jshint anyways).
We should still have about 2 outdated modules (`mozlog` and `mysql`, both with patch level version bumps -- not that we really care right now):
```
$ npm run outdated
> mozilla-chronicle@0.1.0 outdated /Users/pdehaan/dev/github/chronicle
> npm outdated --depth 0
Package  Current  Wanted  Latest  Location
mozlog     1.0.0   1.0.0   1.0.1  mozlog
mysql      2.5.3   2.5.3   2.5.4  mysql
```

chore(build): Updating a couple dependencies and removing jshint devDep

---

.gitattributes

This change will exclude npm-shrinkwrap.json from the output of `git diff` as well as `git log -p`.
Got the idea from [SO](http://stackoverflow.com/questions/1016798/excluding-files-from-git-diff).
Thoughts?

chore(git): exclude npm-shrinkwrap.json from git diffs

---

server/db/db.js

Yikes, dunno how I missed this.
We want to return the paged visit data in reverse chronological order: newest records first, older records later.
To test this PR actually fixed the pagination behavior:
1. `node server/db/create_db.js`
2. `node server/db/create_test_data.js --count 100` to get several pages of records
3. `npm start`
4. the first page of data should start at number 99 and move backwards through time to number 75: `localhost:8080/v1/visits`
5. grab the ID from the last item on the first page, put it in the URL, and you should see the second page of results, from number 74 to number 50: `localhost:8080/v1/visits?visitId=whatever`
@nchapman mind having a look?

bug(api): correctly sort visits

---

server/index.js
server/visits.js

Fixes #65.
This hides the server error text when the logging level is set to anything lower than 'trace', as well as the one log call that was spitting out the fxaId in one of the visits routes.

bug(server): reduce server verbosity

---

docs/API.md
npm-shrinkwrap.json
server/bell_oauth_profile.js
server/config.js
server/db/db.js
server/db/utils.js
server/index.js
server/routes.js
server/routes/auth.js
server/routes/base.js
server/routes/index.js
server/routes/visits.js
server/visits.js

I tried to be a bit more descriptive in the commit messages, as it was a little late to make this stuff a set of atomic commits, but I still wanted to capture some extra detail. I'll just paste those in as a PR description.
When doing local development with the test user, this patch lets you simply surf to /auth/login and a session cookie will be set, skipping the oauth flow completely. All other funky special casing code is gone. Dang, that's nice. (Normally, hitting /auth/login redirects to another endpoint, which redirects to the fxa oauth flow, which eventually ends with a cookie being set, if the oauth stuff worked out successfully.)
Comments welcome!
-----
chore(server): fixup auth
Correctly use Bell to handle the OAuth nonce. Correctly set and validate
cookies (both that the fxaId …

Fixup auth

---

.travis.yml
package.json

Now the I-will-never-fail `grunt validate-shrinkwrap` task won't get run on every commit via the pre-commit hook.
I just saved you 2s per commit. You're welcome.
Fixes #95

chore(build): renaming npm validate task to validate-shrinkwrap

---

server/index.js

Turned out to be easier than thought, as the paths didn't have any existing trailing slashes; so just a quick config change.
FIxes #73

fix(server): strip trailing slashes from server routes

---

.travis.yml
server/db/create_db.sh

So here's what I was thinking as a quick fix for specifying the user in the `create_db.sh` script. Good enough for now?

fix(build): Added optional user param to create_db.sh

---

server/models/models.js

Closes some unclosed Postgres pool connections. A quick search shows 9 instances of `done)` arguments and an equal number of `done()` callback invocations.
> **note:** if you do not call `done()` the client will never be returned to the pool and you will leak clients. This is mega-bad so always call `done()`
> &mdash; via https://github.com/brianc/node-postgres/wiki/pg#connectfunction-callback
Fixes #213

fix(db): closing some db pool connections

---

config/local.json.example
npm-shrinkwrap.json
package.json
server/config.js
server/controllers/search.js
server/controllers/visit.js
server/controllers/visits.js
server/models/visits.js

@nchapman r?
- add url2png package, update npm shrinkwrap
- add url2png keys to config
- add screenshotUrl to visit, visits, and search items
- implemented as a view-level transform (not in the DB)
- this patch introduces some duplication, but I want to separate the "get it working" task from the "make it pretty" refactoring task
- also fix a stray SQL error in `server/models/visits` that I missed with yesterday's giant PR

feat(api): add url2png to provide screenshots

---

server/bell-oauth-profile.js

Seems like the fix for FxA sign in was just renaming the fetched user object. I'm going to merge this right away so I can fix the dev server unless someone is really quick to object :smile:.

fix(server): Fixes FxA sign in

---

app/styles/.scss-lint.yml
app/styles/modules/_global_header.scss
app/styles/modules/_row.scss
app/styles/modules/_visit.scss
package.json

For more info on **scss-lint**, see https://github.com/causes/scss-lint.
It requires Ruby, so it doesn't make sense to add this to any "lint" workflows, but it is available as a npm script convenience method (`npm run scss-lint`) if you already have **scss-lint** installed locally.
Current output is this (but I don't agree with merging):
```
app/styles/modules/_visit.scss:115 [W] Merge rule `&.small + &.small` with rule on line 94
```

chore(sass): tweaking some styles per scss-lint feedback

---

app/scripts/config.js
app/scripts/lib/image_proxy.js
app/scripts/presenters/visit_presenter.js
app/scripts/templates/visits/item.html
app/scripts/views/visits/item.js
app/styles/modules/_visit.scss

This adds Embedly Display as an image proxy on the front-end. This should fix any mixed content warnings over https and does a little work to serve retina images when appropriate (could be brittle). This also replaces our use of CSS to "crop" images using background cover. This makes images actual img tags instead of scumbag background images.

feat(front-end): Adds image proxy via embedly

---

app/scripts/models/user.js
app/scripts/templates/global_header/user_info.html
app/scripts/views/global_header/user_info.js
app/styles/modules/_global_header.scss

This should be merged after #265.
* * *
Adds user info box to the header. Looks like this right now:
Obviously not awesome yet, but ready for @johngruen to style up. We can have that happen in this branch or just merge this and clean up later. Either works for me.

feat(front-end): Adds user info data with avatar to header

---

.jshintrc
app/scripts/views/visits/index.js
app/scripts/views/visits/item.js

This should be merged after #265 and #266.
* * *
Here's a take on endless scrolling for visits. I wish it could be simplified further, but it at least does the job for now. It doesn't do anything to keep the back button working so we'll need to fix that in another pass (or target=blank all the things).
@6a68 let me know what you think about this... We can do something simpler if you think that's better.

feat(front-end): Endless scrolling of visits

---

server/db/postgres.js
server/models/visit.js

@nchapman @pdehaan r?
TL;DR: visit deletion was busted because of the bug fixed by this patch.
The visit.delete model code was expecting an integer count to be returned by postgres, but `{count: <int>}` was getting returned instead. By the laws of javascript insanity, the code then declared shenanigans, told itself that `count > 0` was definitely not true, and, thus, decided that it was time to delete the user_page, when in fact visits still existed that corresponded to said user_page. That led to a postgres error being thrown and unhandled (because the visits table references the user_pages table as a foreign key, and we do _not_ cascade deletes, in order to avoid accidentally nuking data thanks to exactly this kind of bug!). I suspect/hope the DB connection leakage was happening when …

Properly delete visits

---

.travis.yml
README.md
bin/create_db.sh
bin/migrate.js
npm-shrinkwrap.json
package.json
server/db/etl/index.js
server/db/migrations/patch-0-1.sql
server/db/migrations/patch-1-0.sql
server/db/migrations/patch-1-2.sql
server/db/migrations/patch-2-1.sql
server/db/migrator.js

Fixes #92
@nchapman @pdehaan r?
Seems to be working locally for me. If you want to play around with migrations to different levels, we currently have 0, 1, and 2; just do `./bin/migrate.js 0` or whichever int you'd like.
This does not solve the reindexing problem for elasticsearch, that will be in followup issue #291.

feat(db): add migrations support

---

server/controllers/base.js

Fixes #219.
So this feels like a hack, but it dawned on me that if we just reply with a string then hapi doesn't know the modification date and our caching problems go away. I'm ok with trashing this if there's a better way :smiley:.

fix(server): Removes caching for root path

---

app/app.html
app/index.html
app/scripts/main.js
app/scripts/views/home/home.js
grunttasks/requirejs.js

This enables js on the home page. I'm not sure we'll keep this boot sequence for long, but it should work for now until our needs are more complicated.
Fixes #310.
@6a68 r?

chore(front-end): Enables js on the home page

---

README.md
server/config.js
server/db/elasticsearch.js
server/db/migrations/patch-1-2.sql
server/db/migrations/patch-2-3.sql
server/db/migrations/patch-3-2.sql
server/db/migrator.js
server/db/reindex.js
server/embedly.js

@nchapman @pdehaan r?
Since we're only using one worker for now, I didn't bother integrating this into the work queue. However, I did make sure all the job variables were passed into the "worker" as the params object. Should be pretty straightforward to move this into the queue later.
Also made a couple of minor adjustments to the DB, should be self-explanatory, except the rgb -> hex conversion was added because I saw elasticsearch complaining, and might have some impact on the front-end code (if we're using the favicon colors). Note that they're stored without the leading '#'.

Issue 291 reindex on migrate

---

server/models/visits.js

Fixes #324 
@nchapman mind taking a look? Seems to be working for me:

bug(search): include description when searching

---

app/app.html
app/scripts/config.js
app/scripts/lib/modal_manager.js
app/scripts/main.js
app/scripts/router.js
app/scripts/templates/welcome.html
app/scripts/views/visits/index.js
app/scripts/views/welcome.js
app/styles/_modules.scss
app/styles/_state.scss
app/styles/modules/_global_header.scss
app/styles/modules/_modal.scss
app/styles/modules/_welcome.scss
bower.json
config/local.json.example
server/config.js
server/controllers/auth.js

This adds the authenticated portion of the onboarding flow at `/#welcome`. If you're a new user to Chronicle, you'll be directed here after your account is created. This is purposely unstyled and therefore ready for @johngruen to turn it into something much better. It doesn't do a whole lot for now, but will at least help you get the add-on installed in Firefox.
Fixes #247.
@6a68 @johngruen r?

feat(front-end): Adds welcome with add-on installation

---

config/local.json.example
grunttasks/sass.js
server/config.js

Added a useless knob to control your Sass `outputStyle`. Possibly only useful to me and @johngruen (or anybody else dabbling in CSS who doesn't want to read minimized code).
The output is still compressed/minimized by default, but you can easily override locally by setting the `"sass_outputStyle": "nested"` in your config/local.json file.
Fixes #301

chore(sass): Add a convict flag to specify Sass output style

---

README.md
bin/migrate.js
grunttasks/copyright.js
grunttasks/jscs.js
grunttasks/jshint.js
grunttasks/jsonlint.js

Updated README.md to mention the new location of the database scripts in ./bin/.
Also noticed that we weren't linting any of the JavaScript scripts in /bin/ since there weren't any previously.
Fixes #316

docs(readme): update README to use current bin scripts

---

app/scripts/views/visits/date_divider.js

Per http://momentjs.com/docs/#/parsing/string-format/
| Input | Example | Description |
|----:|----|----|
| `Do` | `1st..31st` | Day of month with ordinal |
Fixes #348

fix(visit): Change date heading to use day of month with ordinal

---

npm-shrinkwrap.json
package.json

Updating [**grunt-sass**](https://github.com/sindresorhus/grunt-sass/) ([CHANGELOG](https://github.com/sindresorhus/grunt-sass/compare/v0.17.0...v0.18.0)) and [**wreck**](https://github.com/hapijs/wreck/) ([CHANGELOG](https://github.com/hapijs/wreck/compare/v5.1.0...v5.2.0)) dependencies.
Chronicle should now run on iojs and Node 0.12! (tested w/ iojs-v1.2.0 and v0.12.0)!
Fixes #321

chore(deps): Update grunt-sass dependency

---

npm-shrinkwrap.json
package.json

Replacing **precommit-hook** module with [**husky**](https://www.npmjs.com/package/husky) so we can remove some sketchy automated JSHint logic included in **precommit-hook** and convert the hook from "pre-commit" to "pre-push". See https://github.com/mozilla/chronicle/issues/322 for some more context.
This doesn't address the core issue of #322 (_"git pre-commit linter should only run on files in the git index"_), but should give a slight performance bump (if you like to `git commit` a lot and `git push` a little).
To install/test this, I recommend cleaning out any existing git hooks in your ./.git/hooks/ directory that may have been set up by **precommit-hook** _before_ running `npm install`. The **husky** npm install will recreate any hooks that it watches (notably "precommit", …

chore(build): replace precommit-hook with husky for auto linting

---

bin/create_test_data.js

Each successive test data visit should be +5 hours later than the previous one, giving us 5-6 entries per date heading.
FWIW, 5 [hours] is a magically random number that I made up with no significance, apart from using 2, 3, 4, 6, or 8 were all divisible by 24, giving us the exact same numbers of entries per day. Or we could increase this to an equally arbitrary 7 or 9 hours difference, if that floats your collective boats.
Fixes #345

refactor(db): Change the test data time interval so we see more date headings

---

npm-shrinkwrap.json
package.json
server/index.js
server/routes/auth.js
server/routes/base.js
server/routes/index.js
server/routes/ops.js
server/routes/profile.js
server/routes/search.js
server/routes/ver.js
server/routes/visit.js
server/routes/visits.js

Adds a <http://localhost:8080/docs> route which shows some auto-generated route documentation using [**Lout**](https://www.npmjs.com/package/lout).
It ain't pretty, but _meh_.
Closes #108

feat(docs): add a /docs route using Lout
