- app/index.html
Also added a missing `</div>` so that we pass a basic HTML lint.
Fixes #62
> fix: Updating the copyright year and adding repo link

- grunttasks/clean.js
- grunttasks/copy.js
- grunttasks/watch.js
- server/config.js
> chore(build): Added images directory to grunt tasks

- app/scripts/config.js
- grunttasks/build.js
- grunttasks/template.js
- grunttasks/watch.js
- npm-shrinkwrap.json
- package.json
Fixes #47.
This could end up being brittle, but it does the job for now. We can reassess this if our requirements become more complex.
@pdehaan r?
> chore(build): Embed config values in compiled JavaScript

- .jshintrc
- README.md
- config/local.json.example
- npm-shrinkwrap.json
- package.json
- server/config.js
- server/db/create_db.js
- server/db/create_test_data.js
- server/db/db.js
- server/db/utils.js
- server/index.js
- server/visits.js
This PR is kind of crazy; I might start submitting large PRs with a series of nice-looking atomic commits, just to make them easier to read and review.
I'll add comments inline.
Not sure who wants it, @nchapman? @pdehaan?
> feat(server): add visits API, temporarily relax auth.

- .jshintrc
- app/scripts/collections/visits.js
- app/scripts/models/visit.js
- app/scripts/templates/visits/index.html
- app/scripts/templates/visits/item.html
- app/scripts/views/visits/index.js
- app/scripts/views/visits/item.js
Visualized visits are here!
You'll need to have run `server/db/create_test_data.js` to see anything at all.
@pdehaan @6a68 r?
> feat(front-end): Added basic views for actually viewing visits.

- docs/API.md
Formatted preview: https://github.com/mozilla/chronicle/wiki/API-and-DB-notes
> docs(api): first pass at Visits API docs

- npm-shrinkwrap.json
- package.json
Updating the last 2 outdated modules, as per #70 comment.
> chore(build): Updating mozlog and mysql dependencies

- server/db/db.js
Typo: changing `updateVisit` to `deleteVisit`.
> fix(logging): Fixing the deleteVisit logging message

- README.md
> fix(docs): Adding note about grunt-cli requirement

- app/app.html
- app/index.html
- server/routes/base.js
We'll have to figure out the JS story on the home page, but this is the simplest thing that works for now.
@6a68 r?
Fixes #69
> feat(front-end): Added sign in and sign out links

- .jshintignore
- grunttasks/usemin.js
- server/db/create_db.js
- server/db/create_test_data.js
- server/db/db.js
- server/db/utils.js
- server/routes/base.js
- server/routes/visits.js
> chore(build): Cleaning up some unused vars and eslint warnings

- app/app.html
- grunttasks/requirejs.js
Fallout from the great index.html -> app.html refactor of #107
> fix(requirejs): Fixing requirejs config on app.html

- server/index.js
> bug(server): emit 401 on auth failure, not 302

- README.md
- server/config.js
- server/db/create_test_data.js
> docs: Removing instances of MySQL from the repo

- README.md
- server/config.js
- server/controllers/profile.js
- server/routes/profile.js
> Issue 229 add profile endpoint

- server/models/visits.js
Fixes #227 
Stole @nchapman's v0 search query, let's rock!
> fix(db): improve elasticsearch query

- config/local.json.example
- npm-shrinkwrap.json
- package.json
- server/bell-oauth-profile.js
- server/config.js
- server/work-queue/jobs/index.js
- server/work-queue/jobs/send-welcome-email.js
Questions:
- [**sendmail**](https://www.npmjs.com/package/sendmail) vs [**nodemailer**](https://www.npmjs.com/package/nodemailer) -- It looks like nodemailer has support for different transport options (such as Amazon SES via [**nodemailer-ses-transport**](https://github.com/andris9/nodemailer-ses-transport)), plugins (DKIM), HTML+plaintext...
- When should we use SES vs just SMTP? Currently just has a big `if (config.get('env') === 'local') {...}` block, but not sure if we should use SMTP when `env` is "test".
- There has to be a better way of doing templates than my hacky thing of using `_.template` (since we were already requiring underscore in package.json). Not sure if we should be using Handlebars or something else. I need to dig into what content/auth server is doing to see if …
> WIP: send welcome email

- Gruntfile.js
- app/scripts/config.js
- bin/create_test_data.js
- config/local.json.example
- config/local.json.travis
- server/bell-oauth-profile.js
- server/config.js
- server/controllers/auth.js
- server/controllers/base.js
- server/controllers/search.js
- server/controllers/visit.js
- server/controllers/visits.js
- server/db/elasticsearch.js
- server/db/postgres.js
- server/embedly.js
- server/index.js
- server/logger.js
- server/models/user.js
- server/models/visits.js
- server/routes/auth.js
- server/routes/base.js
- server/routes/ops.js
- server/work-queue/jobs/extract-page.js
- server/work-queue/jobs/send-welcome-email.js
- server/work-queue/queue.js
Fixes #220 
Seems to be working for me locally. @pdehaan mind taking a look?
> bug(ops): flatten convict configs per ops request

- app/app.html
- app/scripts/collections/search_results.js
- app/scripts/models/user_page.js
- app/scripts/presenters/user_page_presenter.js
- app/scripts/router.js
- app/scripts/templates/global_header/global_header.html
- app/scripts/templates/global_header/search_box.html
- app/scripts/templates/global_header/user_info.html
- app/scripts/templates/search/index.html
- app/scripts/templates/user_pages/item.html
- app/scripts/templates/visits/index.html
- app/scripts/views/global_header/global_header.js
- app/scripts/views/global_header/search_box.js
- app/scripts/views/global_header/user_info.js
- app/scripts/views/search/index.js
- app/scripts/views/search/item.js
- app/scripts/views/visits/item.js
- app/styles/_layout.scss
- app/styles/_modules.scss
- app/styles/modules/_global_header.scss
- app/styles/modules/_search_result.scss
- app/styles/modules/_user_page.scss
Working search results are here! Lots of new views. The header is now a little stack of specialized views. The visit presenter has been reworked as a user page presenter. Tried to share a reasonable amount of code between visits and search. I avoided making many scss changes since @johngruen is working on that in a separate branch.
> feat(front-end): Working search box and results

- app/scripts/main.js
- app/scripts/templates/visits/date_divider.html
- app/scripts/views/visits/date_divider.js
- app/scripts/views/visits/index.js
- app/styles/modules/_global_header.scss
- bower.json
This should be merged after #265, #266, and #267.
* * *
Date dividers for visits with really basic relative dates (Today and Yesterday).
> feat(front-end): Adds date dividers to visits

- app/scripts/templates/global_header/global_header.html
- app/scripts/templates/global_header/search_box.html
- app/scripts/templates/user_pages/item.html
- app/styles/_layout.scss
- app/styles/_mixins.scss
- app/styles/_state.scss
- app/styles/_variables.scss
- app/styles/main.scss
- app/styles/modules/_global_header.scss
- app/styles/modules/_row.scss
- app/styles/modules/_user_page.scss
> refactor(styles): start making things sassy, flexy, responsive

- app/scripts/presenters/user_page_presenter.js
- app/scripts/templates/global_header/search_box.html
- app/scripts/templates/user_pages/item.html
- app/scripts/views/visits/index.js
- app/styles/_layout.scss
- app/styles/modules/_user_page.scss
Fixes are here!
@6a68 @johngruen @pdehaan r?
> fix(front-end): Fixed regressions and tweaked small things

- app/scripts/views/visits/index.js
> fix(front-end): Fixes endless scroll in Firefox

- .travis.yml
> chore(build): Adding lint task to Travis

- app/app.html
- app/scripts/templates/global_header/global_header.html
- app/styles/_breakpoints.scss
- app/styles/_variables.scss
- app/styles/main.scss
- app/styles/modules/_global_header.scss
- app/styles/modules/_row.scss
- app/styles/modules/_user_info.scss
@nchapman: This seems like a good solution...what do you think?
> style(breakpoints): add basic breakpoint logic

- app/styles/.scss-lint.yml
- app/styles/modules/_user_page.scss
> fix(styles): fixing invalid width in scss

- config/local.json.example
- server/config.js
- server/index.js
Fixes #248
@nchapman @pdehaan r?
> bug(server): change default session to one month

- server/controllers/ver.js
- server/routes/ver.js
> feat(server): adding a /ver.json route

- server/models/visits.js
> bug(search): include title, extractedLead, extractedUrl, and extractedProviderUrl when searching

- app/styles/_base.scss
- app/styles/modules/_actions.scss
- app/styles/modules/_home.scss
- app/styles/modules/_user_info.scss
- app/styles/modules/_user_page.scss
> fix(style): single row items are too tall

- app/styles/_base.scss
- app/styles/_layout.scss
- app/styles/_modules.scss
- app/styles/_variables.scss
- app/styles/modules/_actions.scss
- app/styles/modules/_home.scss
- app/styles/modules/_search_result.scss
- app/styles/modules/_user_info.scss
- app/styles/modules/_user_page.scss
- app/styles/modules/_visits.scss
This should get merged after #340
>  style(dates): make date markers pretty

- docs/signoff.md
Converted from a wiki page to a markdown file in /docs/.
> docs(signoff): create Chronicle Prerelease Deployment Checklist

- config/local.json.example
- server/bell-oauth-profile.js
- server/config.js
- server/controllers/auth.js
Currently returning a 401 with a nice error string, we could do more.
Fixes #128.
> feat(server): restrict access to whitelisted users
